# @package _group_

hydra:
  run:
    dir: .

defaults:
    - task: null
    - model: null
    - criterion: cross_entropy
    - optimizer: null
    - lr_scheduler: fixed
    - tokenizer: null
    - common_eval: null