common:
  all_gather_list_size: 2048000
  log_interval: 100
  # wandb_entity: ecg-qa
  # wandb_project: question-answering-llm

common_eval:
  path: ???
  quiet: false
  model_overrides: "{'model_path': None, 'no_pretrained_weights': False}"

dataset:
  num_workers: 0
  max_tokens: null
  batch_size: 128
  valid_subset: "valid"
  fixed_validation_seed: 1

task:
  _name: ecg_question_answering
  model_name: null
  data: ???
  normalize: false
  enable_padding: true

model: null